name:                json-cache
version:             0.1.0.0
github:              "mtaylor91/json-cache"
license:             BSD3
author:              "Mike Taylor"
maintainer:          "mike.charles.taylor@gmail.com"
copyright:           "2023 Mike Taylor"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/mtaylor91/json-cache#readme>

dependencies:
- aeson >= 2.0 && < 3
- base >= 4.7 && < 5
- http-types >= 0.12 && < 1
- stm >= 2.5 && < 3
- text >= 1.2 && < 2
- vector >= 0.12 && < 1
- wai >= 3.2 && < 4
- warp >= 3.3 && < 4
- yaml >= 0.11 && < 1

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  json-cache-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - json-cache

tests:
  json-cache-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - json-cache
